////
START GENERATED ATTRIBUTES
WARNING: This content is generated by running npm --prefix .build run generate:attributes
////

//OpenShift Application Services
:org-name: Application Services
:product-long-rhoas: OpenShift Application Services
:community:
:imagesdir: ./images
:property-file-name: app-services.properties
:samples-git-repo: https://github.com/redhat-developer/app-services-guides
:base-url: https://github.com/redhat-developer/app-services-guides/tree/main/docs/

//OpenShift Application Services CLI
:rhoas-cli-base-url: https://github.com/redhat-developer/app-services-cli/tree/main/docs/
:rhoas-cli-ref-url: commands
:rhoas-cli-installation-url: rhoas/rhoas-cli-installation/README.adoc

//OpenShift Streams for Apache Kafka
:product-long-kafka: OpenShift Streams for Apache Kafka
:product-kafka: Streams for Apache Kafka
:product-version-kafka: 1
:service-url-kafka: https://console.redhat.com/application-services/streams/
:getting-started-url-kafka: kafka/getting-started-kafka/README.adoc
:kafka-bin-scripts-url-kafka: kafka/kafka-bin-scripts-kafka/README.adoc
:kafkacat-url-kafka: kafka/kcat-kafka/README.adoc
:quarkus-url-kafka: kafka/quarkus-kafka/README.adoc
:nodejs-url-kafka: kafka/nodejs-kafka/README.adoc
:rhoas-cli-getting-started-url-kafka: kafka/rhoas-cli-getting-started-kafka/README.adoc
:topic-config-url-kafka: kafka/topic-configuration-kafka/README.adoc
:consumer-config-url-kafka: kafka/consumer-configuration-kafka/README.adoc
:access-mgmt-url-kafka: kafka/access-mgmt-kafka/README.adoc
:metrics-monitoring-url-kafka: kafka/metrics-monitoring-kafka/README.adoc
:service-binding-url-kafka: kafka/service-binding-kafka/README.adoc

//OpenShift Service Registry
:product-long-registry: OpenShift Service Registry
:product-registry: Service Registry
:registry: Service Registry
:product-version-registry: 1
:service-url-registry: https://console.redhat.com/application-services/service-registry/
:getting-started-url-registry: registry/getting-started-registry/README.adoc
:quarkus-url-registry: registry/quarkus-registry/README.adoc
:rhoas-cli-getting-started-url-registry: registry/rhoas-cli-getting-started-registry/README.adoc
:access-mgmt-url-registry: registry/access-mgmt-registry/README.adoc
:content-rules-registry: https://access.redhat.com/documentation/en-us/red_hat_openshift_service_registry/1/guide/9b0fdf14-f0d6-4d7f-8637-3ac9e2069817[Supported Service Registry content and rules]
:service-binding-url-registry: registry/service-binding-registry/README.adoc

//OpenShift Connectors
:product-long-connectors: OpenShift Connectors
:service-url-connectors: https://console.redhat.com/application-services/connectors
////
END GENERATED ATTRIBUTES
////

[id="chap-kafka-apis"]
= Interacting with {product-long-kafka} using APIs
ifdef::context[:parent-context: {context}]
:context: kafka-apis

// Purpose statement for the assembly
[role="_abstract"]
As a developer or administrator, you can use the following {product-long-kafka} REST APIs to interact with Kafka instances and other resources in your {product-kafka} environment:

//@comment: Come back and update all API links once they're on console dot. (Stetson)
* https://api.openshift.com/?urls.primaryName=kafka%20service%20fleet%20manager%20service#/[Kafka Service Fleet Manager REST API]: Use this API to interact with Kafka instances and service accounts, view instance metrics, and retrieve general instance information.
* https://github.com/redhat-developer/app-services-sdk-go/blob/main/.openapi/kafka-admin-rest.yaml[Kafka Admin REST API]: Use this API to interact Kafka topics, consumer groups, and Access Control Lists (ACLs), and retrieve information for specific Kafka instances.

//Additional line break to resolve mod docs generation error, not sure why. Leaving for now. (Stetson, 20 May 2021)

[id="con-kafka-fleet-manager-api_{context}"]
== Kafka Service Fleet Manager REST API

The https://api.openshift.com/?urls.primaryName=kafka%20service%20fleet%20manager%20service#/[Kafka Service Fleet Manager REST API] in {product-long-kafka} supports operations for interacting with Kafka instances, service accounts, and other resources for all instances.

For example, the API supports the following operations:

* Create, return, update, or delete Kafka instances
* Create, return, update, or delete service accounts
* Return metrics for Kafka instances
* Return general information about Kafka instances, such as cloud providers
* Return API errors

Fleet Manager REST API requests require the following components:

Authentication::
The Fleet Manager REST API uses OAuth 2.0 token-based authentication and requires the client ID and client secret for your service account. If you don't have a service account or need to regenerate the credentials, use the *Service Accounts* page in the {product-kafka} web console to add or find your service account and update the credentials.
+
--
After you obtain your service account credentials, in the Admin API Swagger page, click *Authorize* or select the lock icon for a specific endpoint and enter the client ID and client secret.

For more information about creating service accounts and client credentials, see {base-url}{getting-started-url-kafka}[Getting started with {product-long-kafka}^].
--

HTTP headers::
The Fleet Manager REST API requires the following HTTP headers for API requests:
+
* `Accept`: Data format accepted by your requesting client:
** `application/json` (JSON)
* `Content-Type`: Data format of your `POST` or `PATCH` API request data:
** `application/json` (JSON)

HTTP methods::
The Fleet Manager REST API supports the following HTTP methods for API requests:
+
* `GET`: Retrieves specified information from a specified resource endpoint
* `POST`: Updates a resource
* `PATCH`: Updates or creates a resource
* `DELETE`: Deletes a resource

Base URL::
The base URL for Fleet Manager REST API requests is `\https://api.openshift.com/`.

Endpoints::
The Fleet Manager REST API endpoints, such as `/api/kafkas_mgmt/v1/kafkas/{id}` for a specified Kafka instance, are the URIs that you append to the Admin REST API base URL to access the corresponding resource in {product-long-kafka}.
+
--
.Example request URL for `/api/kafkas_mgmt/v1/kafkas/{id}` endpoint
`\https://api.openshift.com/api/kafkas_mgmt/v1/kafkas/my-kafka-instance`
--

Request parameters and request data::
Many Fleet Manager REST API requests require specific parameters in the request URL path to identify or filter specific resources and to perform specific actions. You can append URL parameters to the endpoint in the format `?<PARAM>=<VALUE>&<PARAM>=<VALUE>`.
+
--
.Example GET request URL with parameters
`\https://api.openshift.com/api/kafkas_mgmt/v1/kafkas/my-kafka-instance?cloud_provider=aws&id=1iSY6RQ3JKI8Q0OTmjQFd3ocFRg&status=ready`

HTTP `POST` and `PATCH` requests may additionally require a request body or file with data to accompany the request.

.Example POST request URL and JSON request body data to update instance owner
`\https://api.openshift.com/api/kafkas_mgmt/v1/kafkas/my-kafka-instance`

[source,json]
----
{
  "owner": "string",
  "reauthentication_enabled": true
}
----
--

[id="con-kafka-admin-api_{context}"]
== Kafka Admin REST API

The https://github.com/redhat-developer/app-services-sdk-go/blob/main/.openapi/kafka-admin-rest.yaml[Kafka Admin REST API] in {product-long-kafka} supports operations for interacting with topics, consumer groups, Access Control Lists (ACLs), and other resources for specific Kafka instances.

For example, the API supports the following operations:

* Create, return, update, or delete topics
* Create, return, update, or delete consumer groups
* Create, return, update, or delete ACLs
* Produce and records (messages) to and from topics

Admin REST API requests require the following components:

Authentication::
The Admin REST API uses OAuth 2.0 token-based authentication and requires the client ID and client secret for your service account. If you don't have a service account or need to regenerate the credentials, use the *Service Accounts* page in the {product-kafka} web console to add or find your service account and update the credentials.
+
--
After you obtain your service account credentials, in the Admin API Swagger page, click *Authorize* or select the lock icon for a specific endpoint and enter the client ID and client secret.

For more information about creating service accounts and client credentials, see {base-url}{getting-started-url-kafka}[Getting started with {product-long-kafka}^].
--

HTTP headers::
The Admin REST API requires the following HTTP headers for API requests:
+
* `Accept`: Data format accepted by your requesting client:
** `application/json` (JSON)
* `Content-Type`: Data format of your `POST` or `PATCH` API request data:
** `application/json` (JSON)

HTTP methods::
The Admin REST API supports the following HTTP methods for API requests:
+
* `GET`: Retrieves specified information from a specified resource endpoint
* `POST`: Updates a resource
* `PATCH`: Updates or creates a resource
* `DELETE`: Deletes a resource

Base URL::
The base URL for Admin REST API requests is `\https://api.openshift.com/`.

Endpoints::
The Admin REST API endpoints, such as `/api/v1/topics/{topicName}` for a specified Kafka topic, are the URIs that you append to the Admin REST API base URL to access the corresponding resource in {product-long-kafka}.
+
--
.Example request URL for `/api/kafkas_mgmt/v1/topics/{topicName}` endpoint
`\https://api.openshift.com/api/kafkas_mgmt/v1/topics/my-kafka-topic`
--

Request parameters and request data::
Many Admin REST API requests require specific parameters in the request URL path to identify or filter specific resources and to perform specific actions. You can append URL parameters to the endpoint in the format `?<PARAM>=<VALUE>&<PARAM>=<VALUE>`.
+
--
.Example GET request URL with parameters
`\https://api.openshift.com/api/kafkas_mgmt/v1/topics/my-kafka-topic?numPartitions=2&min.insync.replicas=1&max.message.bytes=1050000`

HTTP `POST` and `PATCH` requests may additionally require a request body or file with data to accompany the request.

.Example PATCH request URL and JSON request body data to update a topic
`\https://api.openshift.com/api/kafkas_mgmt/v1/kafkas/my-kafka-topic`

[source,json]
----
{
  "numPartitions": 2,
  "config": [
    {
      "key": "min.insync.replicas",
      "value": "1"
    },
    {
      "key": "max.message.bytes",
      "value": "1050000"
    }
  ]
}
----
--

[id='proc-kafka-api-requests-swagger_{context}']
= Sending Kafka API requests using the Swagger interface

The {product-long-kafka} REST APIs support Swagger web interfaces that you can use instead of a standalone REST client or curl utility to interact with your Kafka instances and other resources.

.Prerequisites
* You have provided the necessary authentication for the relevant API (such as a bearer token or client credentials).

.Procedure
. Select from the following list of API Swagger pages:
+
* https://api.openshift.com/?urls.primaryName=kafka%20service%20fleet%20manager%20service#/[Kafka Service Fleet Manager REST API] (for Kafka instances, service accounts, metrics, and general instance information)
* https://github.com/redhat-developer/app-services-sdk-go/blob/main/.openapi/kafka-admin-rest.yaml[Kafka Admin REST API] (for Kafka topics, consumer groups, Access Control Lists (ACLs), and information for specific Kafka instances)
. In the Swagger page, select the relevant API endpoint to which you want to send a request. For example, in the Fleet Manager REST API, use *default* -> *[GET] /api/kafkas_mgmt/v1/kafkas* to retrieve a list of Kafka instances.
. Click *Try it out* and follow the instructions to provide any optional parameters by which you want to filter results, if needed.
. Click *Execute* and review the response.
+
--

*<@john: From here down is placeholder info from another API doc in BA that I just kept here for now, and it's the direction I was going. Specifically, choosing an endpoint to do something to using the Swagger request, then taking a part of the result of that to make a subsequent request as shown afterward, all to complete a realistic use case for the API. This way it can show different endpoints with different methods in one procedure. But whatever you decide.>*

.Example server response (JSON):
[source,json]
----
{
  "type": "SUCCESS",
  "msg": "List of created containers",
  "result": {
    "kie-containers": {
      "kie-container": [
        {
          "container-id": "itorders_1.0.0-SNAPSHOT",
          "release-id": {
            "group-id": "itorders",
            "artifact-id": "itorders",
            "version": "1.0.0-SNAPSHOT"
          },
          "resolved-release-id": {
            "group-id": "itorders",
            "artifact-id": "itorders",
            "version": "1.0.0-SNAPSHOT"
          },
          "status": "STARTED",
          "scanner": {
            "status": "DISPOSED",
            "poll-interval": null
          },
          "config-items": [],
          "container-alias": "itorders"
        }
      ]
    }
  }
}
----
--
. For this example, copy or note the project `group-id`, `artifact-id`, and `version` (GAV) data from one of the deployed KIE containers returned in the response.
. In the Swagger page, navigate to the *KIE Server and KIE containers* -> *[PUT] /server/containers/{containerId}* endpoint to send another request to deploy a new KIE container with the copied project GAV data. Adjust any request details according to your use case.
. Click *Try it out* and enter the following components for the request:
+
--
* *containerId*: Enter the ID of the new KIE container, such as `MyContainer`.
* *body*: Set the *Parameter content type* to the desired request body format, such as *application/json* for JSON format, and add a request body with the configuration items for the new KIE container:

.Example request body to <TBD @john>
[source,json]
----
{
  "config-items": [
    {
      "itemName": "RuntimeStrategy",
      "itemValue": "SINGLETON",
      "itemType": "java.lang.String"
    },
    {
      "itemName": "MergeMode",
      "itemValue": "MERGE_COLLECTIONS",
      "itemType": "java.lang.String"
    },
    {
      "itemName": "KBase",
      "itemValue": "",
      "itemType": "java.lang.String"
    },
    {
      "itemName": "KSession",
      "itemValue": "",
      "itemType": "java.lang.String"
    }
  ],
  "release-id": {
    "group-id": "itorders",
    "artifact-id": "itorders",
    "version": "1.0.0-SNAPSHOT"
  },
  "scanner": {
    "poll-interval": "5000",
    "status": "STARTED"
  }
}
----
--
. In the *Response content type* drop-down menu, select the desired format of the server response, such as *application/json* for JSON format.
. Click *Execute* and review the {KIE_SERVER} response.
+
--
.Example server response (JSON):
[source,json]
----
{
  "type": "SUCCESS",
  "msg": "Container MyContainer successfully deployed with module itorders:itorders:1.0.0-SNAPSHOT.",
  "result": {
    "kie-container": {
      "container-id": "MyContainer",
      "release-id": {
        "group-id": "itorders",
        "artifact-id": "itorders",
        "version": "1.0.0-SNAPSHOT"
      },
      "resolved-release-id": {
        "group-id": "itorders",
        "artifact-id": "itorders",
        "version": "1.0.0-SNAPSHOT"
      },
      "status": "STARTED",
      "scanner": {
        "status": "STARTED",
        "poll-interval": 5000
      },
      "config-items": [],
      "messages": [
        {
          "severity": "INFO",
          "timestamp": {
            "java.util.Date": 1540584717937
          },
          "content": [
            "Container MyContainer successfully created with module itorders:itorders:1.0.0-SNAPSHOT."
          ]
        }
      ],
      "container-alias": null
    }
  }
}
----

If you encounter request errors, review the returned error code messages and adjust your request accordingly.

--

[role="_additional-resources"]
.Additional resources
* {base-url}{getting-started-url-kafka}[Getting started with {product-long-kafka}^]
* {base-url}{rhoas-cli-getting-started-url-kafka}[Getting started with the `rhoas` CLI for {product-long-kafka}^]
* {rhoas-cli-base-url}{rhoas-cli-ref-url}[CLI command reference (rhoas)^]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
